version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - paperless
      - dave
    command:
      - --certresolv.cloudflare.acme.storage=/acme.json #File needs specific permissions: 600, dockeruser:user
    ports:
      - 80:80
      - 443:443
    environment: # Config for Cloudflare
      - CF_API_EMAIL=<<>>
      - CF_DNS_API_TOKEN=<<>>
      # - CF_API_KEY=YOUR_API_KEY
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - <<>>/traefik/traefik.yml:/traefik.yml:ro
      - <<>>/traefik/acme.json:/acme.json
      - <<>>/traefik/config.yml:/config.yml:ro
    labels:
      - net.unraid.docker.icon="https://raw.githubusercontent.com/ibracorp/unraid-templates/master/icons/traefik.png"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`<<>>`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=<<>>"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`<<>>`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=<<>>"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=<<>>"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  paperless:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.16.50.0/24
#          gateway: 172.16.50.1
  dave:
    driver: bridge